### ISSUE TITLE
Option to use custom tag opener/closer on formatter level

### ISSUE THREAD

**Issue by sh4nks** [dcwatson/bbcode#18]
Hey! 
It would be cool if there would be an option to change the tag_opener and tag_closer on formatter level. Or instead of this, a regex that matches for example an emoji (like ``:smile:`` or ``:)``).
Sorry if this is already available but I couldn't find it.. just had a quick look on the source and in the docs this isn't mentioned.

Thanks!

**Comment by dcwatson** [comment]
I think this might be a little out of scope for a bbcode library. It's pretty easy to apply regex substitutions before or after formatting, and I'd rather not turn this into a general text transformation library. Thanks for the feedback, though!
