### ISSUE TITLE
url should allow specifying target and rel attributes 

### ISSUE THREAD

**Issue by rbu** [dcwatson/bbcode#19]
It would be nice if we could replace

```
[url=example.com]page[/url]
```

with this:
`<a href="http://example.com/" target="_blank" rel="nofollow">link</a>`

by setting an config option to the BBCode instance.

**Comment by dcwatson** [comment]
I'm not sure how many bells and whistles I want to tack on to the default url tag implementation, considering you can do whatever you like by creating your own. To see how the default one works:

https://github.com/dcwatson/bbcode/blob/master/bbcode.py#L156

That said, this isn't the first request for custom behavior, so maybe it's worth making something like a template string that the default url tag can use. Something along the lines of `Parser.url_template = '<a href="%s">%s</a>'` that the default implementation could use.

**Comment by rbu** [comment]
@dcwatson, any update on this? I could provide a PR if you haven't started on this yet and you'd consider merging it

**Comment by dcwatson** [comment]
A PR would be much appreciated.

**Comment by dcwatson** [comment]
Implemented by #28
